# @package _global_
# Override configuration for fair_mon dataset
dataset_name: fair_mon
robot_type: allegro
viewer: rerun-mujoco
embodiment_type: right
task: cat
rerun_spawn: true
ref_dt: 0.05
max_sim_steps: -1
horizon: 1.6
ctrl_dt: 0.4
knot_dt: 0.4
num_dr: 1
perturb_torque: 0.0
pos_noise_scale: 0.03
rot_noise_scale: 0.05
joint_noise_scale: 0.5
improvement_threshold: 0.001
max_num_iterations: 16
